theme: jekyll-theme-minimal
title: WoW/Fumo website test
description: A test site to learn how-to!

include_newlines: |
            Si sta
            Come d'autunno
            Sugli alberi
            Le foglie
